vsphere_user     = "username"
vsphere_password = "password"
vsphere_server   = "localhost"

datacenter    = "DC0"
cluster       = "DC0_H0"
datastore     = "datastore/LocalDS_0"
resource_pool = "DC0_H0/Resources"
network       = "network/VM Network"

vm_name     = "vcsimtest4"
vm_template = "DC0_H0_VM0"
// vm_template = "vcsimtest2"
// vm_folder   = "vm"
vm_password = "xxx"
